### PR TITLE
i12 feat: restructure as formal Python package for ease of use

### LINKED ISSUE #12: Restructure codebase into formal package structure
Making installation and use easier.

### LINKED ISSUE #16: Ensure smoother coder operation when input fields are missing
Currently, blank inputs for either sector or tasks crashes code_data_frame()

### PR DESCRIPTION
**Pull request by jeroenminderman**
Fixes #12 and #16

**_Summary of key changes -_** 
- Changed main module name from `occupationcoder` to `oc3i` for convenience reasons
- Restructured repo so that it can be installed as a user-level package as well as used in developer mode (ie so that modules can be imported easily by external scripts
    - Main package code now housed in src/oc3i/...
    - Updated all file referencing accordingly
    - Moved from `requirements.txt` to `pyproject.toml`
- Updated `.devcontainer` setup so that it follows the above
- Updated README to reflect changes above
- Added function to check input dataframe, and correctly flag and handle missing values (which should fix #16)

**_Note that -_** 
- Currently ISCO source XLSX is not included in the package install
- build_dict.py needs some revision and we should probably move to e.g. Quarto documentation for it instead of a .ipynb notebook.
- ~~Need to do a single quick update to tests so that output file works~~. 
- When merging into main need to change pip install git+... line to use `main` as installation target branch.

### CODE REVIEW

File: .devcontainer/system_setup.sh
Comment (ianbandaons) [inline .devcontainer/system_setup.sh:1]: maybe we could add this comment at the top of the script

# Sets up a Python development environment by creating a virtual environment,
# upgrading pip, and installing the current package in editable mode.

File: README.md [hunk 1]
```diff
@@ -22,75 +22,97 @@ The code contained within this repository is provided 'as is'. We stress that -
...
 ```
-Note that the `scheme` arguments looks for a directory with the same name under [occupationcoder/dictionaries](occupationcoder/dictionaries/). Out of the box, we provide the dictionaries for the SOC scheme as used by the original package, and we have added corresponding ISCO dictionaries.
 
-> The __dictionaries included in this repositories are provided as examples only and should not be considered as official versions of any occupation coding scheme: it is the sole responsibility of the user of this codebase to check whether the dictionaries used are correct and suitable for their use case__.
-
-By default, [coder.py](occupationcoder/coder.py) provides "long" output, i.e. including TF-IDF scores for each fuzzy prediction (note that these are not given if an exact match is found). To suppress outputting scores, set the `output` argument to "single" instead of "multi":
+To install the package and its dependencies directly from this repository, use:
 ```
-python occupationcoder/coder.py --in_file="tests/test_vacancies.csv" --scheme="isco" --output="single"
+pip install git+https://github.com/datasciencecampus/occupationcoder-international.git@i12_feat
```
Comment (ianbandaons) [inline README.md:53]: will need to change the branch after we merge this branch?

Comment (jeroenminderman) [reply README.md:53]: Yes, will do that when merging in to `main`. This was just to make it work temporarily for the PR.

File: .devcontainer/system_setup.sh
Comment (jeroenminderman) [reply .devcontainer/system_setup.sh:1]: Fixed in [#d7709d5](https://github.com/datasciencecampus/occupationcoder-international/commit/994989c610e76a23f5f4f7bf2391341eb174ec95)

File: README.md [hunk 2]
```diff
@@ -22,75 +22,97 @@ The code contained within this repository is provided 'as is'. We stress that -
...
 ```
-python occupationcoder/coder.py --help
+import pandas as pd
+from oc3i import Coder
+from oc3i.coder import get_example_file
+
+coder = Coder(scheme = "isco")
+
+dat = pd.read_csv(get_example_file())
+coder.code_data_frame(dat,
```
[the remark this answers is not in the document]
Comment (jeroenminderman) [reply README.md:71]: Fixed in [#d7709d5](https://github.com/datasciencecampus/occupationcoder-international/commit/994989c610e76a23f5f4f7bf2391341eb174ec95)

File: src/oc3i/coder.py [hunk 3]
```diff
@@ -327,6 +373,9 @@ def parallel_code_data_frame(
         client.close()
         return result
 
+def get_example_file():
+    """Path to the bundled example dataset."""
+    return files("oc3i.data") / "test_vacancies.csv"
```
Comment (josh-ons2022) [inline src/oc3i/coder.py:378]: Should this be hardcoded? Or better to leave flexible?

File: README.md [hunk 4]
```diff
@@ -22,84 +22,119 @@ The code contained within this repository is provided 'as is'. We stress that -
...
-For each row in the input data set, `occupationcoder` will attempt to find an exact match in the given coding scheme. If one is found, the appropriate code from the coding scheme will be returned.
-If no exact match is found, three best "fuzzy" matches using TF-IDF will be returned, using information combined from `job_title`, `job_description` and `job_sector`.
+Once installed, you can use `occupationcoder-international` either through the provided Command Line Interface (CLI) script, or by importing and using the package in your own Python code.
 
-### Running in the command line
+An example code snippet that imports package modules and uses this to code [example input data](src/oc3i/data/test_vacancies.csv) provided is as follows:
+```
+import pandas as pd
+from oc3i import Coder
+from oc3i.coder import get_example_file
```
Comment (josh-ons2022) [inline README.md:63]: Would it be easier to already have this in a script already? 
image

**Review by josh-ons2022 — COMMENTED** [review]
Hey Jeroen ran fine for me on a fresh install. Just added some small points to make more user friendly potentially

File: README.md [hunk 5]
```diff
@@ -22,84 +22,119 @@ The code contained within this repository is provided 'as is'. We stress that -
...
+source env/Scripts/activate
 ```
 
-### Input format
-
-Expected data input is as per the [tests/test_vacancies.csv](tests/test_vacancies.csv) file. Three columns, with headers and content as follows:
-- `job_title`: Specific title of the job to code. `occupationcoder` will use this to attempt an exact match against any specific job titles listed in the target scheme. This is the only field that is treated separately and used for an attempt at an exact match.
-- `job_description`: Expected to be a extended description of the given job, including e.g. tasks or further context. E.g. where `job_title` is "dentist", `job_description` might be "providing dental care to patients".
-- `job_sector`: industrial/sectoral description for the given job. E.g. "medical".
+To install the package and its dependencies directly from this repository, use:
```
[the remark this answers is not in the document]
Comment (jeroenminderman) [reply README.md:51]: You don't have to be - as this is a package install, you don't need a repository for it?
